"""
Django settings for bingosync project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
import urllib.parse
import dj_database_url

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

IS_PROD = os.getenv('DEBUG', '').lower() not in ('1', 'yes')
IS_TEST = len(sys.argv) > 1 and sys.argv[1] == "test"

# SECRET_KEY: Use environment variable in production, default for dev/test
if IS_TEST:
    SECRET_KEY = '1234-test-secret-key'
else:
    SECRET_KEY = os.getenv("SECRET_KEY", None if IS_PROD else '1234')
ADMINS = os.getenv("ADMINS")
SERVER_EMAIL = os.getenv("SERVER_EMAIL")

# Internal API authentication secret
# Used for Django-Tornado communication
INTERNAL_API_SECRET = os.getenv("INTERNAL_API_SECRET")
if not INTERNAL_API_SECRET and not IS_TEST:
    raise ValueError(
        "INTERNAL_API_SECRET environment variable is required. "
        "This secret is used to authenticate internal API calls between Django and Tornado. "
        "Generate a secure random string (32+ characters) using: "
        "python -c 'import secrets; print(secrets.token_urlsafe(32))'")
if INTERNAL_API_SECRET and len(INTERNAL_API_SECRET) < 32 and not IS_TEST:
    raise ValueError(
        "INTERNAL_API_SECRET must be at least 32 characters long for security. "
        "Current length: " + str(len(INTERNAL_API_SECRET))
    )

# Use a test secret for testing
if IS_TEST and not INTERNAL_API_SECRET:
    INTERNAL_API_SECRET = 'test-secret-for-testing-purposes-only-32-chars'

# PostgreSQL-only database configuration
# DATABASE_URL is required and must point to a PostgreSQL database
DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL and not IS_TEST:
    raise ValueError(
        "DATABASE_URL environment variable is required. "
        "Please set it to a valid PostgreSQL connection string. "
        "Example: postgresql://user:password@localhost:5432/bingosync"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PROD

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
CSRF_TRUSTED_ORIGINS = []
if "DOMAIN" in os.environ:
    domain = os.environ["DOMAIN"]
    ALLOWED_HOSTS.append(domain)
    CSRF_TRUSTED_ORIGINS = [f"https://{domain}", f"http://{domain}"]
if "HTTP_SOCK" in os.environ:
    ALLOWED_HOSTS.append(urllib.parse.quote_plus(os.environ['HTTP_SOCK']))

# Email Configuration for Password Reset
# For development, emails will be printed to console
# For production, configure these environment variables:
# - EMAIL_BACKEND: Email backend to use (default: console for dev, smtp for prod)
# - EMAIL_HOST: SMTP server hostname (e.g., smtp.gmail.com)
# - EMAIL_PORT: SMTP server port (default: 587 for TLS)
# - EMAIL_HOST_USER: SMTP username
# - EMAIL_HOST_PASSWORD: SMTP password
# - EMAIL_USE_TLS: Use TLS encryption (recommended: True)
# - DEFAULT_FROM_EMAIL: Email address to send from

if DEBUG:
    # In development, print emails to console instead of sending
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # In production, use SMTP
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND',
                              'django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = os.getenv(
        'EMAIL_USE_TLS',
        'True').lower() in (
        'true',
        '1',
        'yes')
    EMAIL_USE_SSL = os.getenv(
        'EMAIL_USE_SSL',
        'False').lower() in (
        'true',
        '1',
        'yes')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@bingosync.com')

# Password reset token expiry (in seconds)
# Default: 86400 seconds = 24 hours
PASSWORD_RESET_TIMEOUT = 86400


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'bootstrap3',
    'crispy_bootstrap3',
    'bingosync'
)

# Custom User Model
AUTH_USER_MODEL = 'bingosync.User'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

MIDDLEWARE = (
    'bingosync.middleware.RequestLoggingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'bingosync.middleware.SecurityHeadersMiddleware',  # Add CSP headers
    'bingosync.middleware.NotAuthenticatedMiddleware',
    'bingosync.middleware.InvalidRequestMiddleware',
)

# CSRF Protection Settings
# Enable secure CSRF cookies in production
if IS_PROD:
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_HTTPONLY = True
    CSRF_COOKIE_SAMESITE = 'Lax'
    SESSION_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'

# Security Headers
# Enforce HTTPS in production (but not in tests)
if IS_PROD and not IS_TEST:
    SECURE_SSL_REDIRECT = True
else:
    SECURE_SSL_REDIRECT = False  # Explicitly disable in dev/test

# HSTS (HTTP Strict Transport Security)
# Tells browsers to only access the site via HTTPS for 1 year
if IS_PROD:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
else:
    SECURE_HSTS_SECONDS = 0  # Disable HSTS in dev/test

# Prevent MIME type sniffing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enable browser XSS filter
SECURE_BROWSER_XSS_FILTER = True

# Prevent site from being embedded in frames (clickjacking protection)
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy (CSP) Headers
# These will be added via middleware
CSP_DEFAULT_SRC = ("'self'",)
# Minimize inline scripts where possible
CSP_SCRIPT_SRC = ("'self'", "'unsafe-inline'")
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
CSP_IMG_SRC = ("'self'", "data:")
CSP_FONT_SRC = ("'self'",)
# CSP_CONNECT_SRC is set dynamically after SOCKETS_URL is configured
CSP_FRAME_ANCESTORS = ("'none'",)  # Equivalent to X-Frame-Options: DENY

ROOT_URLCONF = 'bingosync.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + "/templates"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bingosync.context_processors.stubtag',
            ],
        },
    },
]

WSGI_APPLICATION = 'bingosync.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# PostgreSQL 15+ is required

if IS_TEST:
    # Use SQLite for tests if DATABASE_URL is not provided
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': ':memory:',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Logging
# https://docs.djangoproject.com/en/1.8/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '\u001b[1m{levelname:4.4} {module}.{funcName}:\u001b[0m {message}',
            'style': '{'
        },
        'verbose': {
            'format': '\u001b[1m{levelname:4.4} {asctime} {module}.{funcName}:\u001b[0m {message}',
            'style': '{'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'django.server': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        'bingosync': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}


if IS_TEST:
    import logging
    logging.disable(logging.CRITICAL)

# base directory for data consumed in tests
TESTDATA_DIR = os.path.join(BASE_DIR, "testdata")

# base directory for data consumed in test_generator.py
GEN_TESTDATA_DIR = os.path.join(TESTDATA_DIR, "gen_output")


if IS_TEST or DEBUG:
    GENERATOR_TIMEOUT_SECONDS = 2
else:
    GENERATOR_TIMEOUT_SECONDS = 10


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

# STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static/'),
)

STATIC_ROOT = os.getenv(
    "STATIC_ROOT",
    os.path.join(
        os.path.dirname(BASE_DIR),
        'static'))


INTERNAL_SOCKETS_URL = "127.0.0.1:8888"

if IS_PROD:
    SOCKETS_URL = "wss://" + os.getenv("SOCKETS_DOMAIN", INTERNAL_SOCKETS_URL)
else:
    SOCKETS_URL = "ws://" + os.getenv("SOCKETS_DOMAIN", INTERNAL_SOCKETS_URL)

# used for publishing events from django to tornado, so can always go
# across localhost
if "WS_SOCK" in os.environ:
    SOCKETS_PUBLISH_URL = (
        f"http+unix://{urllib.parse.quote_plus(os.environ['WS_SOCK'])}")
else:
    # In Docker, use the service name for internal communication
    SOCKETS_PUBLISH_HOST = os.getenv(
        "SOCKETS_PUBLISH_HOST",
        INTERNAL_SOCKETS_URL)
    SOCKETS_PUBLISH_URL = "http://" + SOCKETS_PUBLISH_HOST

# Update CSP to allow WebSocket connections
SOCKETS_DOMAIN = os.getenv("SOCKETS_DOMAIN", INTERNAL_SOCKETS_URL)
if IS_PROD:
    CSP_CONNECT_SRC = ("'self'", f"wss://{SOCKETS_DOMAIN}")
else:
    CSP_CONNECT_SRC = ("'self'", f"ws://{SOCKETS_DOMAIN}")


# crispy forms confiuguration
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# NOTE: django.setup() was previously called here to work around parallel test issues
# However, this causes "populate() isn't reentrant" errors when running tests
# The test runner calls django.setup() automatically, so this is not needed
# django.setup()
