"""
Django settings for bingosync project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import sys
import urllib.parse
import dj_database_url

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

IS_PROD = os.getenv('DEBUG', '').lower() not in ('1', 'yes')

SECRET_KEY = os.getenv("SECRET_KEY", None if IS_PROD else '1234')
ADMINS = os.getenv("ADMINS")
SERVER_EMAIL = os.getenv("SERVER_EMAIL")

# PostgreSQL-only database configuration
# DATABASE_URL is required and must point to a PostgreSQL database
DATABASE_URL = os.getenv("DATABASE_URL")
if not DATABASE_URL:
    raise ValueError(
        "DATABASE_URL environment variable is required. "
        "Please set it to a valid PostgreSQL connection string. "
        "Example: postgresql://user:password@localhost:5432/bingosync"
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not IS_PROD

IS_TEST = len(sys.argv) > 1 and sys.argv[1] == "test"

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
CSRF_TRUSTED_ORIGINS = []
if "DOMAIN" in os.environ:
    domain = os.environ["DOMAIN"]
    ALLOWED_HOSTS.append(domain)
    CSRF_TRUSTED_ORIGINS = [f"https://{domain}", f"http://{domain}"]
if "HTTP_SOCK" in os.environ:
    ALLOWED_HOSTS.append(urllib.parse.quote_plus(os.environ['HTTP_SOCK']))

EMAIL_HOST = "localhost"
EMAIL_PORT = 25


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'bootstrap3',
    'crispy_bootstrap3',
    'bingosync'
)

MIDDLEWARE = (
    'bingosync.middleware.RequestLoggingMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'bingosync.middleware.NotAuthenticatedMiddleware',
    'bingosync.middleware.InvalidRequestMiddleware',
)

ROOT_URLCONF = 'bingosync.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR + "/templates"
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'bingosync.context_processors.stubtag',
            ],
        },
    },
]

WSGI_APPLICATION = 'bingosync.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
# PostgreSQL 15+ is required

DATABASES = {
    'default': dj_database_url.parse(DATABASE_URL)
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Los_Angeles'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Logging
# https://docs.djangoproject.com/en/1.8/topics/logging/

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '\u001b[1m{levelname:4.4} {module}.{funcName}:\u001b[0m {message}',
            'style': '{'
        },
        'verbose': {
            'format': '\u001b[1m{levelname:4.4} {asctime} {module}.{funcName}:\u001b[0m {message}',
            'style': '{'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
        'django.server': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'ERROR'),
            'propagate': False,
        },
        'bingosync': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
        },
    },
}


if IS_TEST:
    import logging
    logging.disable(logging.CRITICAL)

# base directory for data consumed in tests
TESTDATA_DIR = os.path.join(BASE_DIR, "testdata")

# base directory for data consumed in test_generator.py
GEN_TESTDATA_DIR = os.path.join(TESTDATA_DIR, "gen_output")


if IS_TEST or DEBUG:
    GENERATOR_TIMEOUT_SECONDS = 2
else:
    GENERATOR_TIMEOUT_SECONDS = 10


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.CachedStaticFilesStorage'

STATIC_URL = '/static/'

STATICFILES_DIRS = (
  os.path.join(BASE_DIR, 'static/'),
)

STATIC_ROOT = os.getenv("STATIC_ROOT", os.path.join(os.path.dirname(BASE_DIR), 'static'))


INTERNAL_SOCKETS_URL = "127.0.0.1:8888"

if IS_PROD:
    SOCKETS_URL = "wss://" + os.getenv("SOCKETS_DOMAIN", INTERNAL_SOCKETS_URL)
else:
    SOCKETS_URL = "ws://" + os.getenv("SOCKETS_DOMAIN", INTERNAL_SOCKETS_URL)

# used for publishing events from django to tornado, so can always go across localhost
if "WS_SOCK" in os.environ:
    SOCKETS_PUBLISH_URL = f"http+unix://{urllib.parse.quote_plus(os.environ['WS_SOCK'])}"
else:
    SOCKETS_PUBLISH_URL = "http://" + INTERNAL_SOCKETS_URL


# crispy forms confiuguration
CRISPY_TEMPLATE_PACK = 'bootstrap3'

# Calling django.setup() here works around an issue with running tests in parallel
import django
django.setup()
