# Generated by Django 4.2.28 on 2026-02-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type_value',
            field=models.IntegerField(choices=[(50, 'Harry Potter and the Chamber of Secrets')], default=50, verbose_name='Game Type'),
        ),
        migrations.AlterField(
            model_name='newcardevent',
            name='game_type_value',
            field=models.IntegerField(choices=[(50, 'Harry Potter and the Chamber of Secrets')]),
        ),
    ]
