# Generated by Django 4.2.28 on 2026-02-24 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0003_add_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_also_player',
            field=models.BooleanField(default=False, help_text='For Gamemaster role: allows GM to mark squares', verbose_name='Is Also Player'),
        ),
        migrations.AddField(
            model_name='player',
            name='monitoring_player',
            field=models.ForeignKey(blank=True, help_text='For Counter role: the player being monitored', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counters', to='bingosync.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('gamemaster', 'Gamemaster'), ('player', 'Player'), ('counter', 'Counter'), ('spectator', 'Spectator')], default='player', max_length=20, verbose_name='Role'),
        ),
    ]
