# Generated by Django 4.2.28 on 2026-03-01 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0007_make_email_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked user account (null for anonymous spectators)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rolechangeevent',
            name='player_color_value',
            field=models.IntegerField(choices=[(2, 'Red'), (3, 'Blue'), (4, 'Green'), (5, 'Orange'), (6, 'Purple'), (7, 'Navy'), (8, 'Teal'), (9, 'Pink'), (10, 'Forest'), (11, 'Yellow')]),
        ),
    ]
