# Generated by Django 4.2.28 on 2026-03-03 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0010_remove_is_also_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='square',
            name='claim_status',
            field=models.CharField(choices=[('none', 'None'), ('under_review', 'Under Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='none', help_text='Status of the claim for counter review system', max_length=20, verbose_name='Claim Status'),
        ),
        migrations.AddField(
            model_name='square',
            name='claimed_by',
            field=models.ForeignKey(blank=True, help_text='Player who claimed this square', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_squares', to='bingosync.player'),
        ),
        migrations.AddField(
            model_name='square',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Counter who reviewed this claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_squares', to='bingosync.player'),
        ),
        migrations.AlterField(
            model_name='chatevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='colorevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='connectionevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='filteredpattern',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='goalevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newcardevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='revealedevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rolechangeevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='square',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='square',
            index=models.Index(fields=['game', 'slot'], name='bingosync_s_game_id_d6059d_idx'),
        ),
    ]
