# Generated by Django 4.2.28 on 2026-03-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0012_counterassignmentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatevent',
            name='is_system_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='counterassignmentevent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='counterassignmentevent',
            name='player_color_value',
            field=models.IntegerField(choices=[(2, 'Red'), (3, 'Blue'), (4, 'Green'), (5, 'Orange'), (6, 'Purple'), (7, 'Navy'), (8, 'Teal'), (9, 'Pink'), (10, 'Forest'), (11, 'Yellow')]),
        ),
    ]
