# Generated by Django 4.2.28 on 2026-03-03 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0013_add_system_message_to_chat_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalevent',
            name='claim_status',
            field=models.CharField(default='confirmed', help_text='Status of the claim when event was created', max_length=20, verbose_name='Claim Status'),
        ),
        migrations.CreateModel(
            name='ClaimReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sent')),
                ('player_color_value', models.IntegerField(choices=[(2, 'Red'), (3, 'Blue'), (4, 'Green'), (5, 'Orange'), (6, 'Purple'), (7, 'Navy'), (8, 'Teal'), (9, 'Pink'), (10, 'Forest'), (11, 'Yellow')])),
                ('action', models.CharField(choices=[('under_review', 'Under Review'), ('confirm', 'Confirm'), ('reject', 'Reject')], help_text='Action taken by counter: under_review, confirm, or reject', max_length=20)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingosync.player')),
                ('reviewed_player', models.ForeignKey(help_text='Player whose claim was reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='claim_reviews_received', to='bingosync.player')),
                ('square', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingosync.square')),
            ],
            options={
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
    ]
