# Generated by Django 4.2.30 on 2026-09-13 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0014_goalevent_claim_status_claimreviewevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddIndex(
            model_name='chatevent',
            index=models.Index(fields=['timestamp'], name='bingosync_c_timesta_03c981_idx'),
        ),
        migrations.AddIndex(
            model_name='claimreviewevent',
            index=models.Index(fields=['timestamp'], name='bingosync_c_timesta_5fa6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='colorevent',
            index=models.Index(fields=['timestamp'], name='bingosync_c_timesta_357dc5_idx'),
        ),
        migrations.AddIndex(
            model_name='connectionevent',
            index=models.Index(fields=['timestamp'], name='bingosync_c_timesta_17219b_idx'),
        ),
        migrations.AddIndex(
            model_name='counterassignmentevent',
            index=models.Index(fields=['timestamp'], name='bingosync_c_timesta_e0526a_idx'),
        ),
        migrations.AddIndex(
            model_name='goalevent',
            index=models.Index(fields=['timestamp'], name='bingosync_g_timesta_fa8dfd_idx'),
        ),
        migrations.AddIndex(
            model_name='newcardevent',
            index=models.Index(fields=['timestamp'], name='bingosync_n_timesta_f8af9f_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['room', 'user'], name='bingosync_p_room_id_3e7ee0_idx'),
        ),
        migrations.AddIndex(
            model_name='revealedevent',
            index=models.Index(fields=['timestamp'], name='bingosync_r_timesta_4aacca_idx'),
        ),
        migrations.AddIndex(
            model_name='rolechangeevent',
            index=models.Index(fields=['timestamp'], name='bingosync_r_timesta_483a91_idx'),
        ),
    ]
