# Generated by Django 4.2.30 on 2026-09-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0015_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Player who won this lockout game (first to a majority of confirmed squares); null while the game is unwon', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='bingosync.player'),
        ),
    ]
