# Generated by Django 4.2.30 on 2026-09-27 15:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bingosync', '0016_add_game_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(max_length=16)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_lines', to='bingosync.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_lines', to='bingosync.player')),
            ],
            options={
                'unique_together': {('game', 'player', 'line')},
            },
        ),
    ]
